### ISSUE TITLE
'undefined is not a function' when playing track 

### ISSUE THREAD

**Issue by starkcoffee** [GrooveBoxHH/GrooveBox_Player#14]
I'm using node v0.12.4 and when I posted a track to the player I get this error. Any ideas

```
/Users/duana/projects/GrooveBox_Player/node_modules/player/dist/player.js:270
      this._list.push(latest);
                 ^
TypeError: undefined is not a function
    at Player.add (/Users/duana/projects/GrooveBox_Player/node_modules/player/dist/player.js:270:18)
    at PlayerWrapper.add (/Users/duana/projects/GrooveBox_Player/libs/player_wrapper.js:136:17)
    at PlayerWrapper.addToPlaylist (/Users/duana/projects/GrooveBox_Player/libs/player_wrapper.js:159:14)
    at /Users/duana/projects/GrooveBox_Player/index.js:16:17
    at IncomingMessage.<anonymous> (/Users/duana/projects/GrooveBox_Player/libs/soundcloud_wrapper.js:61:13)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by starkcoffee** [comment]
ok I solved my own problem. I had to create a file called `playlist.dump.json` and I just guessed what the empty contents should be and put `{}`. But I should have put `[]`. I'll update the README.

**Comment by JoschkaSchulz** [comment]
awesome. I never heard about the playlist.dump.json. I think that was Lars part on the weekend. Sorry for missing to add this in the README.

**Comment by starkcoffee** [comment]
no probs! I'm impressed that it works! about to demo it.

**Comment by torasakura** [comment]
more error handling would be nice. i had an url which is not streamable, but instead that the playerWrapper told me about it, i got an indexOf is not a function of undefined error. for testing that's the not streamable url https://soundcloud.com/dropkickmurphys/rose-tattoo

**Comment by JoschkaSchulz** [comment]
After all the refactor of @BeneStem isn't there a problem with the playlist dump so I close this Issue.
